/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import backend.CentroVacinacao;
import backend.Serializacao;
import backend.Sistema;
import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.JOptionPane;


public class GestorAgendaMarcacoes extends javax.swing.JFrame {
    private Sistema sistema;
    private Serializacao bd;
    private CentroVacinacao centro;
    
    /**
     * Creates new form GestorAgendaMarcacoes
     */
    public GestorAgendaMarcacoes(Sistema sistema, Serializacao bd, CentroVacinacao centro) {
        initComponents();
        this.sistema = sistema;
        this.bd = bd;
        this.centro=centro;
        
        //Mostra a centralização da janela
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botaoVoltar = new javax.swing.JButton();
        dataMarcacao = new com.toedter.calendar.JCalendar();
        botaoMarcacoes = new javax.swing.JButton();
        botaoFazerMarc = new javax.swing.JButton();
        botaoRemover = new javax.swing.JButton();
        botaoMarcAmanha = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botaoFaltaram = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(45, 62, 80));

        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        dataMarcacao.setPreferredSize(new java.awt.Dimension(133, 24));

        botaoMarcacoes.setText("Ver marcações");
        botaoMarcacoes.setToolTipText("Selecione um dia!");
        botaoMarcacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMarcacoesActionPerformed(evt);
            }
        });

        botaoFazerMarc.setText("Fazer Marcação");
        botaoFazerMarc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFazerMarcActionPerformed(evt);
            }
        });

        botaoRemover.setText("Remover Marcação");
        botaoRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoverActionPerformed(evt);
            }
        });

        botaoMarcAmanha.setText("Marcações de amanhã");
        botaoMarcAmanha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMarcAmanhaActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(224, 60, 50));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("TABELA DE MARCAÇÕES");

        botaoFaltaram.setText("Utentes que faltaram");
        botaoFaltaram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFaltaramActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(dataMarcacao, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoVoltar)
                        .addGap(69, 69, 69))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(botaoFazerMarc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoMarcacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoMarcAmanha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoFaltaram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(28, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(215, 215, 215))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dataMarcacao, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botaoFazerMarc)
                        .addGap(18, 18, 18)
                        .addComponent(botaoRemover)
                        .addGap(18, 18, 18)
                        .addComponent(botaoMarcacoes)
                        .addGap(18, 18, 18)
                        .addComponent(botaoMarcAmanha)
                        .addGap(18, 18, 18)
                        .addComponent(botaoFaltaram)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoVoltar)
                        .addGap(39, 39, 39))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoMarcacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMarcacoesActionPerformed
        if (dataMarcacao.getDate()!=null){
            LocalDate data =dataMarcacao.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            GestorListaUtenteAgendados j = new GestorListaUtenteAgendados(sistema, bd, centro, data);
            j.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Selecione uma data!");
        }
    }//GEN-LAST:event_botaoMarcacoesActionPerformed

    private void botaoFazerMarcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFazerMarcActionPerformed
        if (dataMarcacao.getDate()!=null){
            if(dataMarcacao.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate().isAfter(LocalDate.now()) || dataMarcacao.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate().isEqual(LocalDate.now())){
                if (centro.getMarcacoes().CalcularNumeroMarcacoes(dataMarcacao.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate())<centro.getNumMaxMarcacoes()){
                    LocalDate data =dataMarcacao.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                    GestorFazerMarcacao j= new GestorFazerMarcacao(sistema, bd, centro, data);
                    j.setVisible(true);
                }else
                    JOptionPane.showMessageDialog(this, "Não há mais marcações disponiveis para esse dia!");
            }else{
                JOptionPane.showMessageDialog(this, "Selecione uma data posterior ao dia de hoje!");
            }
       }else{
            JOptionPane.showMessageDialog(this, "Selecione uma data!");
        }
    }//GEN-LAST:event_botaoFazerMarcActionPerformed

    private void botaoRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverActionPerformed
        if (dataMarcacao.getDate()!=null){
            LocalDate data =dataMarcacao.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            
            if(centro.getMarcacoes().ConsultarMarcacao(data)!=null){
                GestorRemoverMarcacao j = new GestorRemoverMarcacao(sistema, bd, centro, data); 
                j.setVisible(true);
            }else{
               JOptionPane.showMessageDialog(this, "Não existem marcações para esse dia!"); 
            }           
        }else{
            JOptionPane.showMessageDialog(this, "Selecione uma data!");
        }
         
    }//GEN-LAST:event_botaoRemoverActionPerformed

    private void botaoMarcAmanhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMarcAmanhaActionPerformed
         if (dataMarcacao.getDate()!=null){
            LocalDate data= LocalDate.now().plusDays(1);
            GestorListaUtenteAgendados j = new GestorListaUtenteAgendados(sistema, bd, centro, data);
            j.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Selecione uma data!");
        }
    }//GEN-LAST:event_botaoMarcAmanhaActionPerformed

    private void botaoFaltaramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFaltaramActionPerformed
        GestorFaltarMarc j = new GestorFaltarMarc(sistema, bd, centro);
        j.setVisible(true);

    }//GEN-LAST:event_botaoFaltaramActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestorAgendaMarcacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestorAgendaMarcacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestorAgendaMarcacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestorAgendaMarcacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new GestorAgendaMarcacoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoFaltaram;
    private javax.swing.JButton botaoFazerMarc;
    private javax.swing.JButton botaoMarcAmanha;
    private javax.swing.JButton botaoMarcacoes;
    private javax.swing.JButton botaoRemover;
    private javax.swing.JButton botaoVoltar;
    private com.toedter.calendar.JCalendar dataMarcacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
