/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import backend.Administrador;
import backend.CentroVacinacao;
import backend.Gestor;
import backend.ListaCentVac;
import backend.Serializacao;
import backend.Sistema;
import backend.Utente;
import backend.Utilizador;
import javax.swing.JOptionPane;
import javax.swing.UIManager;


public class Principal extends javax.swing.JFrame {
    private Sistema sistema;
    private Serializacao bd;
    
    /**
     * Creates new form Principal
     */
    public Principal(Sistema sistema, Serializacao bd) {
        initComponents();
        
        this.sistema = sistema;
        this.bd = bd;
        
        //Mostra a centralização da janela
        this.setLocationRelativeTo(null);
        
        //Apenas mostra o menu de administração se o utilizador for um administrador
        jAdmin.setVisible(sistema.getUtilizadorLigado() instanceof Administrador);
        
        //Apenas mostra o menu de administração se o utilizador for um gestor
        jGestor.setVisible(sistema.getUtilizadorLigado() instanceof Gestor);
        
        //Apenas mostra o menu de administração se o utilizador for um administrador
        jUtente.setVisible(sistema.getUtilizadorLigado() instanceof Utente);
        
        jPerfilUtente.setVisible(sistema.getUtilizadorLigado() instanceof Utente);
        
        //janela de perfil para alterar dados ao admin e gestor, não aparece no utente
        if (sistema.getUtilizadorLigado() instanceof Utente){
            jPerfil.setVisible(false);
        }
    }
    
    private void guardarAlteracoes() {
        bd.gravaSistema(sistema);
    }

    private void terminar() {
       UIManager.put("OptionPane.noButtonText", "Não");
       UIManager.put("OptionPane.yesButtonText", "Sim");

        if (JOptionPane.showConfirmDialog(null, 
               "Deseja realmente terminar o programa?", 
               "Terminar",

               JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                dispose();
                Login l = new Login(sistema, bd);
                l.setVisible(true);
                guardarAlteracoes();
                dispose();
       }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jGeral = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPerfil = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jPerfilUtente = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jAdmin = new javax.swing.JMenu();
        editarGestores = new javax.swing.JMenuItem();
        editarCentros = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jGestor = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jUtente = new javax.swing.JMenu();
        menuCentro = new javax.swing.JMenuItem();
        menuDoencas = new javax.swing.JMenuItem();
        menuMarcacao = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(399, 327));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(399, 330));

        jPanel1.setBackground(new java.awt.Color(45, 62, 80));
        jPanel1.setPreferredSize(new java.awt.Dimension(399, 327));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel2)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel2)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(224, 60, 50));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(261, 35));

        jGeral.setBackground(new java.awt.Color(224, 60, 50));
        jGeral.setText("Geral");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Guardar Dados");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jGeral.add(jMenuItem1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem3.setText("Terminar");
        jMenuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem3MouseClicked(evt);
            }
        });
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jGeral.add(jMenuItem3);

        jMenuBar1.add(jGeral);

        jPerfil.setBackground(new java.awt.Color(224, 60, 50));
        jPerfil.setText("Perfil");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem6.setText("Alterar dados do utilizador");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jPerfil.add(jMenuItem6);

        jMenuBar1.add(jPerfil);

        jPerfilUtente.setText("Perfil");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Alterar dados");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPerfilUtente.add(jMenuItem2);

        jMenuBar1.add(jPerfilUtente);

        jAdmin.setBackground(new java.awt.Color(224, 60, 50));
        jAdmin.setText("Administrador");

        editarGestores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        editarGestores.setText("Editar Gestores");
        editarGestores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarGestoresMouseClicked(evt);
            }
        });
        editarGestores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarGestoresActionPerformed(evt);
            }
        });
        jAdmin.add(editarGestores);

        editarCentros.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        editarCentros.setText("Editar Centros ");
        editarCentros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarCentrosActionPerformed(evt);
            }
        });
        jAdmin.add(editarCentros);

        jMenuItem13.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem13.setText("Listar Utentes");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jAdmin.add(jMenuItem13);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem9.setText("Vacinas");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jAdmin.add(jMenuItem9);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem10.setText("Estatísticas");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jAdmin.add(jMenuItem10);

        jMenuBar1.add(jAdmin);

        jGestor.setBackground(new java.awt.Color(224, 60, 50));
        jGestor.setText("Gestor");

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem5.setText("Marcações");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jGestor.add(jMenuItem5);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem7.setText("Stock do Centro");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jGestor.add(jMenuItem7);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem8.setText("Estatísticas do Centro");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jGestor.add(jMenuItem8);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem4.setText("O seu Centro");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jGestor.add(jMenuItem4);

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem12.setText("Listagem Utentes");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jGestor.add(jMenuItem12);

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem11.setText("Inoculação");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jGestor.add(jMenuItem11);

        jMenuBar1.add(jGestor);

        jUtente.setBackground(new java.awt.Color(224, 60, 50));
        jUtente.setText("Utente");

        menuCentro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuCentro.setText("O seu Centro");
        menuCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCentroActionPerformed(evt);
            }
        });
        jUtente.add(menuCentro);

        menuDoencas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuDoencas.setText("Registar doencas");
        menuDoencas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDoencasActionPerformed(evt);
            }
        });
        jUtente.add(menuDoencas);

        menuMarcacao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuMarcacao.setText("Marcação");
        menuMarcacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMarcacaoActionPerformed(evt);
            }
        });
        jUtente.add(menuMarcacao);

        jMenuBar1.add(jUtente);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCentroActionPerformed
        Utilizador user =sistema.getUtilizadorLigado();
        Utente utente = (Utente) user;
        if (utente.getCentro()==null){
            UtenteEscolher e = new UtenteEscolher(sistema, bd, utente);
            e.setVisible(true);
        }else{
            UtenteCentro u =new UtenteCentro(sistema, bd, utente);
            u.setVisible(true);
        }
    }//GEN-LAST:event_menuCentroActionPerformed

    private void menuDoencasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDoencasActionPerformed
        Utilizador ligado=sistema.getUtilizadorLigado();
        Utente utente= (Utente) ligado;
        UtenteRegistarDoencas u = new UtenteRegistarDoencas(sistema, bd, utente);
        u.setVisible(true);
    }//GEN-LAST:event_menuDoencasActionPerformed

    private void editarGestoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarGestoresActionPerformed
       AdminListarGestores gestores = new AdminListarGestores(sistema, bd);
       gestores.setVisible(true);
    }//GEN-LAST:event_editarGestoresActionPerformed

    private void editarGestoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarGestoresMouseClicked

    }//GEN-LAST:event_editarGestoresMouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        terminar();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem3MouseClicked
        // TODO add your handling code here:
        setVisible(false);
        Login log = new Login (sistema, bd);
        log.setVisible(true); 
        terminar();
    }//GEN-LAST:event_jMenuItem3MouseClicked

    private void editarCentrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarCentrosActionPerformed
        // TODO add your handling code here:
        AdminCentrosVacinacao cv=new AdminCentrosVacinacao(sistema,bd);
        cv.setVisible(true);
    }//GEN-LAST:event_editarCentrosActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        Utilizador ligado=sistema.getUtilizadorLigado();
        Gestor gestor= (Gestor) ligado;
        if (gestor.getCentroAtribuido()!=null){
            CentroVacinacao centroAtribuido= gestor.getCentroAtribuido();
            GestorStockCentro g = new GestorStockCentro(sistema, bd, centroAtribuido);
            g.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Gestor não tem centro atribuido");
        }
        
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        Utilizador user=sistema.getUtilizadorLigado();
        JanelaDadosUtilizador j = new JanelaDadosUtilizador(sistema, user, bd);
        j.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Utilizador ligado=sistema.getUtilizadorLigado();
        Utente utente= (Utente) ligado;
        UtenteAlterarDados u = new UtenteAlterarDados(sistema, bd, utente);
        u.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        guardarAlteracoes();
        JOptionPane.showMessageDialog(this, "Dados guardados com sucesso!");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        Utilizador ligado=sistema.getUtilizadorLigado();
        Gestor gestor= (Gestor) ligado;
        if (gestor.getCentroAtribuido()!=null){
            CentroVacinacao centroAtribuido= gestor.getCentroAtribuido();
            GestorListarUtentes g = new GestorListarUtentes(sistema, bd, centroAtribuido);
            g.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Gestor não tem centro atribuido");
        }
        
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        Utilizador ligado=sistema.getUtilizadorLigado();
        Gestor gestor= (Gestor) ligado;
        if (gestor.getCentroAtribuido()!=null){
            CentroVacinacao centroAtribuido= gestor.getCentroAtribuido();
            GestorAgendaMarcacoes g = new GestorAgendaMarcacoes(sistema, bd, centroAtribuido);
            g.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Gestor não tem centro atribuido");
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Utilizador user =sistema.getUtilizadorLigado();
        Gestor gestor = (Gestor) user;
        if (gestor.getCentroAtribuido()!=null){
            GestorInfoCentro gi = new GestorInfoCentro(sistema, bd, gestor);
            gi.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Gestor não tem centro atribuido");
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void menuMarcacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMarcacaoActionPerformed
        Utente utente = (Utente)sistema.getUtilizadorLigado();
        CentroVacinacao centro = utente.getCentro();
        
        if(utente.getCentro() == null) {
            JOptionPane.showMessageDialog(this, "Utente não tem centro atribuido");
        }else{
        UtenteMarc um = new UtenteMarc(sistema, bd,utente, centro);
        um.setVisible(true);}
    }//GEN-LAST:event_menuMarcacaoActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        AdminListaVacinas v = new AdminListaVacinas(sistema, bd);
        v.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        Utilizador ligado=sistema.getUtilizadorLigado();
        Gestor gestor= (Gestor) ligado;
        if (gestor.getCentroAtribuido()!=null){
            CentroVacinacao centroAtribuido= gestor.getCentroAtribuido();
            Estatisticas g = new Estatisticas(sistema, bd, centroAtribuido);
            g.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Gestor não tem centro atribuido");
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        Estatisticas a = new Estatisticas(sistema, bd, null);
        a.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        Utilizador ligado=sistema.getUtilizadorLigado();
        Gestor gestor= (Gestor) ligado;
        if (gestor.getCentroAtribuido()!=null){
            CentroVacinacao centroAtribuido= gestor.getCentroAtribuido();
            GestorRegistarVacinacao g;
             try {
                 g = new GestorRegistarVacinacao(sistema, bd, centroAtribuido);
                 g.setVisible(true);
             } catch (ListaCentVac.CentroNaoExistenteException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
             }            
        }else{
            JOptionPane.showMessageDialog(this, "Gestor não tem centro atribuido");
        }                                             
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        AdminListarUtentes al=new AdminListarUtentes(sistema,bd);
        al.setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem editarCentros;
    private javax.swing.JMenuItem editarGestores;
    private javax.swing.JMenu jAdmin;
    private javax.swing.JMenu jGeral;
    private javax.swing.JMenu jGestor;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu jPerfil;
    private javax.swing.JMenu jPerfilUtente;
    private javax.swing.JMenu jUtente;
    private javax.swing.JMenuItem menuCentro;
    private javax.swing.JMenuItem menuDoencas;
    private javax.swing.JMenuItem menuMarcacao;
    // End of variables declaration//GEN-END:variables
}
